# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-12 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_category_slug'),
        ('rango', '0002_auto_20190126_0021'),
        ('rango', '0013_auto_20190123_1230'),
    ]

    operations = [
    ]
